name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (Ensure we have the latest stable version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Neocities CLI globally
      - name: Install Neocities CLI
        run: |
          npm install -g neocities
          echo "Node and npm version:"
          node -v
          npm -v
          echo "Installed packages:"
          npm list -g --depth=0  # List installed npm packages to verify neocities is installed
          echo "PATH:"
          echo $PATH  # Print PATH to check if neocities is in the correct path

      # Step 4: Add Neocities CLI to the PATH (for this specific shell session)
      - name: Add Neocities to PATH
        run: |
          export PATH=$PATH:/opt/hostedtoolcache/node/16.20.2/x64/lib/node_modules/.bin
          echo "Updated PATH: $PATH"
          neocities --version  # Verify the CLI works after updating the PATH

      # Step 5: Deploy to Neocities
      - name: Deploy to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_SECRET_KEY }}
        run: neocities push . --exclude README.md


