name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (Ensure we have the latest stable version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Neocities CLI locally in the project folder
      - name: Install Neocities CLI
        run: |
          npm install neocities  # Local installation
          echo "Node and npm version:"
          node -v
          npm -v
          echo "Installed packages:"
          npm list --depth=0  # List local packages to verify neocities is installed

      # Step 4: Use npx to run Neocities CLI (without needing to modify the PATH)
      - name: Deploy to Neocities with npx
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_SECRET_KEY }}
        run: |
          npx neocities push . --exclude README.md
