name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (Ensure we have the latest stable version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Neocities CLI locally in the project folder
      - name: Install Neocities CLI
        run: |
          npm install neocities  # Local installation
          echo "Node and npm version:"
          node -v
          npm -v
          echo "Installed packages:"
          npm list --depth=0  # List local packages to verify neocities is installed
          echo "PATH:"
          echo $PATH  # Print PATH to check if neocities is in the correct path

      # Step 4: Ensure the Neocities CLI is available in this session
      - name: Add Neocities to PATH
        run: |
          export PATH=$PATH:$(pwd)/node_modules/.bin  # Add local node_modules/.bin to PATH
          echo "Updated PATH: $PATH"
          neocities --version  # Verify if the CLI works after updating the PATH

      # Step 5: Deploy to Neocities
      - name: Deploy to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_SECRET_KEY }}
        run: neocities push . --exclude README.md



